name       : apostrophe
version    : 2.2.0.3
release    : 5
source     :
    - https://gitlab.gnome.org/somas/apostrophe/-/archive/v2.2.0.3/apostrophe-v2.2.0.3.tar.gz : 79b7aa4913eceaf3a81baa23fe1071ae462b17f6b0f77d8e69f3d554474b4cab
homepage   : https://gitlab.gnome.org/somas/apostrophe
license    : GPL-3.0-or-later
component  : office.notes
summary    : Distraction free Markdown editor
description: |
    Apostrophe is a GTK+ based distraction free Markdown editor, mainly developed by Wolf Vollprecht and Manuel Genovés. It uses pandoc as backend for markdown parsing and offers a very clean and sleek user interface.
replaces   :
    - uberwriter
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(gtk+-3.0)
rundeps    :
    - libwebkit-gtk
    - pyenchant
    - python-gobject
    - python-levenshtein
    - python-pypandoc
    - python-regex
    - python3-cairo
setup      : |
    sed -i "s|2.2.0.2|2.2.0.3|g" meson.build #Fix version number
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
