name       : apostrophe
version    : 2.6.3
release    : 11
source     :
    - https://gitlab.gnome.org/World/apostrophe/-/archive/v2.6.3/apostrophe-v2.6.3.tar.gz : 6f73c80146af0820ec705ec8b32ec64f0f323f51de6b6a4cfd4d02f0719876f3
homepage   : https://world.pages.gitlab.gnome.org/apostrophe/
license    : GPL-3.0-or-later
component  : office.notes
summary    : Distraction free Markdown editor
description: |
    Apostrophe is a GTK+ based distraction free Markdown editor, mainly developed by Wolf Vollprecht and Manuel Genovés. It uses pandoc as backend for markdown parsing and offers a very clean and sleek user interface.
replaces   :
    - uberwriter
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(libhandy-1)
    - desktop-file-utils
    - sassc
rundeps    :
    - font-fira-ttf
    - gspell
    - libhandy
    - libwebkit-gtk
    - pyenchant
    - python-gobject
    - python-levenshtein
    - python-pypandoc
    - python-regex
setup      : |
    # Fix export to HTML
    sed -i 's|/app/share/fonts|/usr/share/fonts/truetype/fira|' data/media/css/web/base.css
    
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
