name       : uberwriter
version    : 2.1.2
release    : 1
source     :
    - https://github.com/UberWriter/uberwriter/archive/v2.1.2.tar.gz : b21e3f0e71c762cfe73c70f43818091cd7ac35dea4ed10b1a4d82ecc76c77f2d
license    : GPL-3.0-or-later
component  : office.notes
summary    : Distraction free Markdown editor
description: |
    Uberwriter is a GTK+ based distraction free Markdown editor, mainly developed by Wolf Vollprecht. It uses pandoc as backend for markdown parsing and offers a very clean and sleek user interface.
rundeps    :
    - libwebkit-gtk
    - pandoc
    - pyenchant
    - python3-cairo
    - python3-gobject
    - python-levenshtein
    - python-regex
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-wrong-paths.patch
build      : |
    %python3_setup
install    : |
    %python3_install
