name       : uberwriter
version    : 2.1.5
release    : 2
source     :
    - https://github.com/UberWriter/uberwriter/archive/v2.1.5a.tar.gz : 4af400053437bf9894a000a40ed9c5d66e4cae2f91526123cdd1f08ab58e1bbe
license    : GPL-3.0-or-later
component  : office.notes
summary    : Distraction free Markdown editor
description: |
    Uberwriter is a GTK+ based distraction free Markdown editor, mainly developed by Wolf Vollprecht. It uses pandoc as backend for markdown parsing and offers a very clean and sleek user interface.
rundeps    :
    - libwebkit-gtk
    - pandoc
    - pyenchant
    - python3-cairo
    - python3-gobject
    - python-levenshtein
    - python-regex
build      : |
    %python3_setup
install    : |
    %python3_install
