name       : apostrophe
version    : '2.5'
release    : 7
source     :
    - https://gitlab.gnome.org/World/apostrophe/-/archive/v2.5/apostrophe-v2.5.tar.gz : 366b239ea7bb720c11fc7344827b6739e4983132c9932aa4705a3b88533d75e4
homepage   : https://world.pages.gitlab.gnome.org/apostrophe/
license    : GPL-3.0-or-later
component  : office.notes
summary    : Distraction free Markdown editor
description: |
    Apostrophe is a GTK+ based distraction free Markdown editor, mainly developed by Wolf Vollprecht and Manuel Genovés. It uses pandoc as backend for markdown parsing and offers a very clean and sleek user interface.
replaces   :
    - uberwriter
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(libhandy-1)
    - desktop-file-utils
    - sassc
rundeps    :
    - libwebkit-gtk
    - pyenchant
    - python-gobject
    - python-levenshtein
    - python-pypandoc
    - python-regex
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-homepage.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
